name: Build & Run on Self-Hosted

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test-run:
    # This targets your self-hosted runner
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build & test
        run: mvn -B -q verify

      - name: Package (skip tests)
        run: mvn -B -q -DskipTests package

      - name: Run app
        run: mvn -q exec:java
